INSERT INTO regiones (id, nombre) VALUES (1, 'Sudamérica');
INSERT INTO regiones (id, nombre) VALUES (2, 'Centroamérica');
INSERT INTO regiones (id, nombre) VALUES (3, 'Norteamérica');
INSERT INTO regiones (id, nombre) VALUES (4, 'Europa');
INSERT INTO regiones (id, nombre) VALUES (5, 'Asia');
INSERT INTO regiones (id, nombre) VALUES (6, 'África');
INSERT INTO regiones (id, nombre) VALUES (7, 'Oceanía');
INSERT INTO regiones (id, nombre) VALUES (8, 'Antártida');

INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(1, 'Sergio','Herraiz','sergio@sergio.com','2020-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(2, 'Marijose','Rodriguez','marijose@marijose.com','2020-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(2, 'Carlos','Herraiz','carlos@carlos.com','2020-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(3, 'Miguel','Herraiz','miguel@miguel.com','2020-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(3, 'Carlos','Rodríguez','cr@cr.com','1950-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(4, 'Marita','Naranjo','mn@mn.com','1960-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(4, 'Javier','Alonso','ja@ja.com','1970-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(4, 'Quique','Alonso','qa@qa.com','1980-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(5, 'Elisa','Alonso','ea@ea.com','1990-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(6, 'Diego','Alonso','da@da.com','2000-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(7, 'Maricarmen','Rodríguez','mr@mr.com','2010-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(7, 'Nico','Herraiz','nh@nh.com','2020-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(8, 'Sergio','Herraiz','sergio@sergio.com','2020-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(8, 'Marijose','Rodriguez','marijose@marijose.com','2020-02-18');
INSERT INTO clientes (region_id, nombre, apellido, email, create_at) VALUES(8, 'Carlos','Herraiz','carlos@carlos.com','2020-02-18');